= Core Concepts in Apache Shiro

This part of the documentation covers Shiro's core architectural concepts.

First we'll present Shiro's architecture and a summary of each core concept. Then we'll cover the most important concept in Shiro - the `Subject`, a security-specific 'view' of a <em>single</em> application user. Next we'll discuss the <tt>SecurityManager</tt>, an application singleton that manages all Subjects for the application, and as well as the SecurityManager's supporting components that do most of Shiro's heavy lifting. Then onto Realms, the security-specific DAOs, Shiro communicates with and then Permissions, the building block of any security policy.

* link:architecture.html[Architecture]

* link:subject.html[Subject]

* link:securitymanager.html[SecurityManager]

* link:realm.html[Realms]

* link:permissions.html[Permissions]

== Lend a hand with documentation

While we hope this documentation helps you with the work you're doing with Apache Shiro, the community is improving and expanding the documentation all the time. If you'd like to help the Shiro project, please consider correcting, expanding, or adding documentation where you see a need. Every little bit of help you provide expands the community and in turn improves Shiro.

The easiest way to contribute your documentation is to send it to the http://shiro-user.582556.n2.nabble.com/[User Forum] or the link:mailing-lists.html[User Mailing List].

pass:[<input type="hidden" id="ghEditPage" value="core.adoc"></input>]
